### ISSUE TITLE
dockerfile was not up-to-date

### ISSUE THREAD

**Issue by zhubonan** [aiidateam/aiida-docker-stack#27]
Need to update the dockerfile report to have aiida with more recent versions
[https://github.com/aiidateam/aiida_core_base-docker](url)

**Comment by yakutovicha** [comment]
This is the solution we came up with:

1) [aiida-docker-base](https://github.com/aiidateam/aiida-docker-base) is the base image that contains AiiDA only
2) aiida-docker-stack (this image) will add PostgreSQL and RabbitMQ on top + configure everything to make it ready-to-use
